//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Exam
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ExamDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ExamDbEntities object using the connection string found in the 'ExamDbEntities' section of the application configuration file.
        /// </summary>
        public ExamDbEntities() : base("name=ExamDbEntities", "ExamDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExamDbEntities object.
        /// </summary>
        public ExamDbEntities(string connectionString) : base(connectionString, "ExamDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExamDbEntities object.
        /// </summary>
        public ExamDbEntities(EntityConnection connection) : base(connection, "ExamDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlanksQuestion> BlanksQuestions
        {
            get
            {
                if ((_BlanksQuestions == null))
                {
                    _BlanksQuestions = base.CreateObjectSet<BlanksQuestion>("BlanksQuestions");
                }
                return _BlanksQuestions;
            }
        }
        private ObjectSet<BlanksQuestion> _BlanksQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BoolQuestion> BoolQuestions
        {
            get
            {
                if ((_BoolQuestions == null))
                {
                    _BoolQuestions = base.CreateObjectSet<BoolQuestion>("BoolQuestions");
                }
                return _BoolQuestions;
            }
        }
        private ObjectSet<BoolQuestion> _BoolQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<McQuestion> McQuestions
        {
            get
            {
                if ((_McQuestions == null))
                {
                    _McQuestions = base.CreateObjectSet<McQuestion>("McQuestions");
                }
                return _McQuestions;
            }
        }
        private ObjectSet<McQuestion> _McQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Test> Tests
        {
            get
            {
                if ((_Tests == null))
                {
                    _Tests = base.CreateObjectSet<Test>("Tests");
                }
                return _Tests;
            }
        }
        private ObjectSet<Test> _Tests;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlanksQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlanksQuestions(BlanksQuestion blanksQuestion)
        {
            base.AddObject("BlanksQuestions", blanksQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BoolQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBoolQuestions(BoolQuestion boolQuestion)
        {
            base.AddObject("BoolQuestions", boolQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the McQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMcQuestions(McQuestion mcQuestion)
        {
            base.AddObject("McQuestions", mcQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTests(Test test)
        {
            base.AddObject("Tests", test);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamDbModel", Name="BlanksQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlanksQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlanksQuestion object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static BlanksQuestion CreateBlanksQuestion(global::System.Int32 id)
        {
            BlanksQuestion blanksQuestion = new BlanksQuestion();
            blanksQuestion.ID = id;
            return blanksQuestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CorrectAnswer
        {
            get
            {
                return _CorrectAnswer;
            }
            set
            {
                OnCorrectAnswerChanging(value);
                ReportPropertyChanging("CorrectAnswer");
                _CorrectAnswer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CorrectAnswer");
                OnCorrectAnswerChanged();
            }
        }
        private global::System.String _CorrectAnswer;
        partial void OnCorrectAnswerChanging(global::System.String value);
        partial void OnCorrectAnswerChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamDbModel", Name="BoolQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BoolQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BoolQuestion object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static BoolQuestion CreateBoolQuestion(global::System.Int32 id)
        {
            BoolQuestion boolQuestion = new BoolQuestion();
            boolQuestion.ID = id;
            return boolQuestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ans1
        {
            get
            {
                return _Ans1;
            }
            set
            {
                OnAns1Changing(value);
                ReportPropertyChanging("Ans1");
                _Ans1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ans1");
                OnAns1Changed();
            }
        }
        private global::System.String _Ans1;
        partial void OnAns1Changing(global::System.String value);
        partial void OnAns1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ans2
        {
            get
            {
                return _Ans2;
            }
            set
            {
                OnAns2Changing(value);
                ReportPropertyChanging("Ans2");
                _Ans2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ans2");
                OnAns2Changed();
            }
        }
        private global::System.String _Ans2;
        partial void OnAns2Changing(global::System.String value);
        partial void OnAns2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CorrectAnswer
        {
            get
            {
                return _CorrectAnswer;
            }
            set
            {
                OnCorrectAnswerChanging(value);
                ReportPropertyChanging("CorrectAnswer");
                _CorrectAnswer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CorrectAnswer");
                OnCorrectAnswerChanged();
            }
        }
        private Nullable<global::System.Int32> _CorrectAnswer;
        partial void OnCorrectAnswerChanging(Nullable<global::System.Int32> value);
        partial void OnCorrectAnswerChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamDbModel", Name="McQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class McQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new McQuestion object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static McQuestion CreateMcQuestion(global::System.Int32 id)
        {
            McQuestion mcQuestion = new McQuestion();
            mcQuestion.ID = id;
            return mcQuestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ans1
        {
            get
            {
                return _Ans1;
            }
            set
            {
                OnAns1Changing(value);
                ReportPropertyChanging("Ans1");
                _Ans1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ans1");
                OnAns1Changed();
            }
        }
        private global::System.String _Ans1;
        partial void OnAns1Changing(global::System.String value);
        partial void OnAns1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ans2
        {
            get
            {
                return _Ans2;
            }
            set
            {
                OnAns2Changing(value);
                ReportPropertyChanging("Ans2");
                _Ans2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ans2");
                OnAns2Changed();
            }
        }
        private global::System.String _Ans2;
        partial void OnAns2Changing(global::System.String value);
        partial void OnAns2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ans3
        {
            get
            {
                return _Ans3;
            }
            set
            {
                OnAns3Changing(value);
                ReportPropertyChanging("Ans3");
                _Ans3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ans3");
                OnAns3Changed();
            }
        }
        private global::System.String _Ans3;
        partial void OnAns3Changing(global::System.String value);
        partial void OnAns3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ans4
        {
            get
            {
                return _Ans4;
            }
            set
            {
                OnAns4Changing(value);
                ReportPropertyChanging("Ans4");
                _Ans4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ans4");
                OnAns4Changed();
            }
        }
        private global::System.String _Ans4;
        partial void OnAns4Changing(global::System.String value);
        partial void OnAns4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CorrectAnswer
        {
            get
            {
                return _CorrectAnswer;
            }
            set
            {
                OnCorrectAnswerChanging(value);
                ReportPropertyChanging("CorrectAnswer");
                _CorrectAnswer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CorrectAnswer");
                OnCorrectAnswerChanged();
            }
        }
        private global::System.String _CorrectAnswer;
        partial void OnCorrectAnswerChanging(global::System.String value);
        partial void OnCorrectAnswerChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExamDbModel", Name="Test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Test object.
        /// </summary>
        /// <param name="qID">Initial value of the QID property.</param>
        public static Test CreateTest(global::System.Int32 qID)
        {
            Test test = new Test();
            test.QID = qID;
            return test;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QID
        {
            get
            {
                return _QID;
            }
            set
            {
                if (_QID != value)
                {
                    OnQIDChanging(value);
                    ReportPropertyChanging("QID");
                    _QID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("QID");
                    OnQIDChanged();
                }
            }
        }
        private global::System.Int32 _QID;
        partial void OnQIDChanging(global::System.Int32 value);
        partial void OnQIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CID
        {
            get
            {
                return _CID;
            }
            set
            {
                OnCIDChanging(value);
                ReportPropertyChanging("CID");
                _CID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CID");
                OnCIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CID;
        partial void OnCIDChanging(Nullable<global::System.Int32> value);
        partial void OnCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();

        #endregion
    
    }

    #endregion
    
}
